### ISSUE TITLE
If you don't have a php user password!

### ISSUE THREAD

**Issue by giumbai** [spyrosoft/php-terminal-emulator#1]
If you don't have a php user password you can't use it. That is how i understand it. By default php user doesn't  has any password and most people don't use password for it. Can't it be changed? The design is not so good. But i like it, it's a nice script!

**Comment by spyrosoft** [comment]
RTFM:

Installation
------------

Change the password at the top of the code slightly for security. Copy the password to your clipboard. Drop this file in the desired directory. Paste in the password and have at it.
